In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1CVrRk4--uOQx5iEtAUd798LeJM8g_jxA3qr634guj18/edit?gid=748703564#gid=748703564"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Animation")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

In [3]:
animation_titles = [
    'ANTARCTICA',
'FOO',
'MOOMINS',
'SAPIENS',
'SOME ASSEMBLY REQUIRED',
'STRAY (Film) ',
'THE BROBARIANS (FKA MANTOOTH)',
'TRAP, THE ',
'VALE, THE  (FKA COMA)' ,
'20,000 LEAGUES UNDER THE SEA',
'LIVING THE DREAM',
'NARPS',
'OUTLETS',
'WITCHFELD',
'NIMONA (Film)',
'OUTER WILDS (TV)',
'SAUSAGE PARTY (TV)',
'SAUSAGE PARTY (Film)'
                   ]

In [4]:
df = df.query("Title ==@animation_titles")

In [5]:
df['division_flag'] = 'Animation'

In [6]:
df["Title"] = df["Title"].str.title()

In [7]:
df

,Title,AP DIVISION,Project Stage,AP Lead,AP Jr.,AP Dev,BA Status,Creative Status,Next Milestone,Option Expiration,...,Cast 1,Cast 2,Cast 3,Cast 4,BA Update Time,Creative Status Update Time,Key Timing Update Time,slack_channel_id,links,division_flag
2,Antarctica,"Animation, Film",3. Internal Development,"Andrew, Rob",,,Don Hertzfeldt COA fully executed. Square Peg ...,Square Peg sent the deck and script to Andrew ...,,1/25/2027,...,,,,,8/25/2025 6:55:44,8/25/2025 6:55:53,,C07D0QCHUG6,,Animation
10,Foo,"Animation, Film",3. Internal Development,"Andrew, Rob",,,Option terms closed with Disney. Brad Copeland...,"-story-team presently at 7, with addition of t...",,1/26/2028,...,,,,,7/3/2025 5:46:38,8/25/2025 6:34:16,,C07DDJW23EU,,Animation
51,Moomins,"Animation, Film",3. Internal Development,"Andrew, Rob, Hector, Megan",,,Rebecca Sugar COA+E fully executed. Rights dea...,-Ongoing creative reviews and working sessions...,,9/2/2026,...,,,,,7/3/2025 5:48:29,8/25/2025 6:48:20,8/25/2025 6:48:19,C07D7AQSW1G,,Animation
76,Sapiens,"Animation, TV, Interactive",3. Internal Development,"Pat, Andrew","Jenna, Alex",,Underlying IP and NWEP deals fully executed. K...,-Kate Purdy's deal now up at Amazon and negoti...,TTM EOY,3/1/2026,...,,,,,8/25/2025 5:42:43,7/14/2025 6:41:26,,C07DAE7ET09,,Animation
83,Some Assembly Required,"Animation, Film",3. Internal Development,"Andrew, Rob",,,All current rights deals are executed. Annapur...,Last week we shared the latest SAR beat outlin...,,Original Idea,...,,,,,,7/14/2025 6:55:57,,C093M0QSNAG,,Animation
87,Stray (Film),"Animation, Interactive, Film",3. Internal Development,"Andrew, Rob, Hector, Megan, Leanne",,,N/A,"-Negotiation underway with new writing team, E...",Treatemnt expected 7/11,Owned IP,...,,,,,,8/25/2025 6:51:14,7/1/2025 6:18:49,C07L699RZS9,,Animation
92,The Brobarians (Fka Mantooth),"Animation, Film",3. Internal Development,"Andrew, Rob",,,Work is paused during ongoing negotiations wit...,-Paramount deal closed.\n-Writer deal on cusp ...,Pitching week of 7/21,Original idea,...,,,,,7/1/2025 6:11:56,8/25/2025 6:47:08,7/2/2025 6:19:41,C07LJGUULF4,,Animation
99,"Trap, The","Animation, Film",3. Internal Development,Andrew,,,EDGLRD LOI signed. Co-fi discussion ongoing. C...,-Edglrd connected with Lesher who is the condu...,,Owned IP,...,,,,,8/25/2025 6:53:03,8/25/2025 6:53:11,,C07A18CMKSS,,Animation
110,"20,000 Leagues Under The Sea","Animation, TV",4. Pending Deal,"Andrew, Pat","Katelin, Alex",,"Deal terms closed 5/29, pending review of exte...","-Our team and show-runner, Tom Wheeler, select...",,Public Domain,...,,,,,8/25/2025 5:58:45,8/25/2025 5:59:13,,C09BV2WDPHA,,Animation
111,Living The Dream,"Animation, TV",4. Pending Deal,"Andrew, Pat","Katelin, Alex",,"Deal terms closed 5/29, pending review of exte...","-Pilot, artwork and series bible shared with F...",,4/5/2026,...,,,,,8/25/2025 5:54:09,8/25/2025 5:54:24,,C09BPSX40CD,,Animation
112,Narps,"Animation, TV",4. Pending Deal,"Andrew, Pat","Katelin, Alex",,"Deal terms closed 5/29, pending review of exte...",Working on deal as part of taking over Nick’s ...,,5/4/2027,...,,,,,8/25/2025 5:55:18,7/14/2025 6:45:04,,C09CK41005N,,Animation
122,Outlets,"Animation, TV",4. Pending Deal,"Andrew, Pat","Katelin, Alex",,"Deal terms closed 5/29, pending review of exte...",Working on deal as part of taking over Nick’s ...,,6/5/2027,...,,,,,8/25/2025 5:55:55,7/14/2025 6:45:17,,C09BPT0Q6MB,,Animation
128,Witchfeld,"Animation, TV",4. Pending Deal,"Andrew, Pat","Katelin, Alex",,"Deal terms closed 5/29, pending review of exte...",Working on deal as part of taking over Nick’s ...,,5/6/2027,...,,,,,8/25/2025 5:57:57,8/25/2025 5:58:31,,C09BT5XENDU,,Animation
133,Nimona (Film),"Animation, Film",8. Library,"Andrew, Rob, Megan, Pat",Alex,,No pending deals.,Exploring the idea of a sequel.,,Owned IP,...,,,,,,,,,,Animation
150,Outer Wilds (Tv),"Animation, TV, Interactive",6. Tracking,"Hector, Megan, Pat, Andrew, Rob",Katelin,,,,,Owned IP,...,,,,,,,,,,Animation
154,Sausage Party (Tv),"Animation, TV",8. Library,"Pat, Andrew",Alex,,All deals executed. Waiting on confirmation of...,Season 2 is out!,,Owned IP - with partners,...,Seth Rogen,Kristen Wiig,Michael Sera,,,8/25/2025 5:17:51,5/25/2025 7:34:00,C07D5EGN161,,Animation
162,Sausage Party (Film),"Animation, Film",8. Library,,,,,,,Owned IP - with partners,...,,,,,,,,,,Animation

In [8]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_film_pt"
)

In [9]:
df = df.rename({"title_film_pt":"_id"}, axis=1)

In [10]:
cols = [
    '_id', 
        'ap_division_film_pt', 
        'project_stage_film_pt',
       'ap_lead_film_pt', 
        'ap_jr_film_pt', 
        'ap_dev_film_pt',
       'ba_status_film_pt', 
        'creative_status_film_pt',
       'next_milestone_film_pt', 
        'key_timing_film_pt',
       'option_expiration_film_pt', 
        'key_timing_date_film_pt',
       'underlying_ip_film_pt', 
        'logline_film_pt',
       'platform__distribution_film_pt', 
        'deal_type_film_pt',
       'partners_and_vendors_film_pt', 
        'creators_film_pt', 
        'director_film_pt',
       'writers_film_pt', 
        'producer_1_film_pt', 
        'producer_2_film_pt',
       'cast_1_film_pt', 
        'cast_2_film_pt', 
        'cast_3_film_pt', 
        'cast_4_film_pt',
    'division_flag_film_pt'
       ]

In [11]:
#df["project_stage_film_pt"] = df["project_stage_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_lead_film_pt"] = df["ap_lead_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_jr_film_pt"] = df["ap_jr_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_division_film_pt"] = df["ap_division_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])

In [12]:
df[cols]

,_id,ap_division_film_pt,project_stage_film_pt,ap_lead_film_pt,ap_jr_film_pt,ap_dev_film_pt,ba_status_film_pt,creative_status_film_pt,next_milestone_film_pt,key_timing_film_pt,...,creators_film_pt,director_film_pt,writers_film_pt,producer_1_film_pt,producer_2_film_pt,cast_1_film_pt,cast_2_film_pt,cast_3_film_pt,cast_4_film_pt,division_flag_film_pt
2,Antarctica,"[Animation, Film]",3. Internal Development,"[Andrew, Rob]",[],,Don Hertzfeldt COA fully executed. Square Peg ...,Square Peg sent the deck and script to Andrew ...,,Pitching targeted for Feb,...,Don Hertzfeldt,Don Hertzfeldt,Don Hertzfeldt,Ari Aster & Lars Knudsen,"Jeremy Platt, Christine D'Souza",,,,,Animation
10,Foo,"[Animation, Film]",3. Internal Development,"[Andrew, Rob]",[],,Option terms closed with Disney. Brad Copeland...,"-story-team presently at 7, with addition of t...",,Reels round 1 review on track for March,...,Chris Wedge,Chris Wedge,Chris Wedge,,,,,,,Animation
51,Moomins,"[Animation, Film]",3. Internal Development,"[Andrew, Rob, Hector, Megan]",[],,Rebecca Sugar COA+E fully executed. Rights dea...,-Ongoing creative reviews and working sessions...,,Outline target end of Jan,...,,,Rebecca Sugar,,,,,,,Animation
76,Sapiens,"[Animation, TV, Interactive]",3. Internal Development,"[Pat, Andrew]","[Jenna, Alex]",,Underlying IP and NWEP deals fully executed. K...,-Kate Purdy's deal now up at Amazon and negoti...,TTM EOY,● Second Option Period remaining: $75k for add...,...,,,Kate Purdy,,,,,,,Animation
83,Some Assembly Required,"[Animation, Film]",3. Internal Development,"[Andrew, Rob]",[],,All current rights deals are executed. Annapur...,Last week we shared the latest SAR beat outlin...,,Beat outline delivered 12/10\nPlan to close wi...,...,,Nick Bruno,Paul Downs,,,,,,,Animation
87,Stray (Film),"[Animation, Interactive, Film]",3. Internal Development,"[Andrew, Rob, Hector, Megan, Leanne]",[],,N/A,"-Negotiation underway with new writing team, E...",Treatemnt expected 7/11,● Negotiating new writers (Erica and Bo)\n● An...,...,,Adam Cootes,Mike Vukadinovich,,,,,,,Animation
92,The Brobarians (Fka Mantooth),"[Animation, Film]",3. Internal Development,"[Andrew, Rob]",[],,Work is paused during ongoing negotiations wit...,-Paramount deal closed.\n-Writer deal on cusp ...,Pitching week of 7/21,Early Jan to kick of next phase of Dev,...,,,,,,,,,,Animation
99,"Trap, The","[Animation, Film]",3. Internal Development,[Andrew],[],,EDGLRD LOI signed. Co-fi discussion ongoing. C...,-Edglrd connected with Lesher who is the condu...,,● Sort partners Q1\n● Prepare and sign GL pack...,...,,Harmony Korine,,,,,,,,Animation
110,"20,000 Leagues Under The Sea","[Animation, TV]",4. Pending Deal,"[Andrew, Pat]","[Katelin, Alex]",,"Deal terms closed 5/29, pending review of exte...","-Our team and show-runner, Tom Wheeler, select...",,● Prepare art and store for pitch end of Q1,...,,,,,,,,,,Animation
111,Living The Dream,"[Animation, TV]",4. Pending Deal,"[Andrew, Pat]","[Katelin, Alex]",,"Deal terms closed 5/29, pending review of exte...","-Pilot, artwork and series bible shared with F...",,"● Pitching, Fox 12/16, and courting Amazon",...,,,Luke Strickler,Nick Weidenfeld,,,,,,Animation
112,Narps,"[Animation, TV]",4. Pending Deal,"[Andrew, Pat]","[Katelin, Alex]",,"Deal terms closed 5/29, pending review of exte...",Working on deal as part of taking over Nick’s ...,,Early dev,...,,,Max Barrett,Nick Weidenfeld,,,,,,Animation
122,Outlets,"[Animation, TV]",4. Pending Deal,"[Andrew, Pat]","[Katelin, Alex]",,"Deal terms closed 5/29, pending review of exte...",Working on deal as part of taking over Nick’s ...,,Early dev,...,,,Trevor Wallace,Nick Weidenfeld,,,,,,Animation
128,Witchfeld,"[Animation, TV]",4. Pending Deal,"[Andrew, Pat]","[Katelin, Alex]",,"Deal terms closed 5/29, pending review of exte...",Working on deal as part of taking over Nick’s ...,,Early dev,...,,,Diablo Cody,Nick Weidenfeld,,,,,,Animation
133,Nimona (Film),"[Animation, Film]",8. Library,"[Andrew, Rob, Megan, Pat]",[Alex],,No pending deals.,Exploring the idea of a sequel.,,Early dev,...,,,,,,,,,,Animation
150,Outer Wilds (Tv),"[Animation, TV, Interactive]",6. Tracking,"[Hector, Megan, Pat, Andrew, Rob]",[Katelin],,,,,Early dev,...,,,,,,,,,,Animation
154,Sausage Party (Tv),"[Animation, TV]",8. Library,"[Pat, Andrew]",[Alex],,All deals executed. Waiting on confirmation of...,Season 2 is out!,,S2 released,...,Seth Rogen & Evan Goldberg,Conrad Vernon,"Kyle Hunter, Ariel Shaffir, Seth Rogen & Evan ...",Sony,Point Grey,Seth Rogen,Kristen Wiig,Michael Sera,,Animation
162,Sausage Party (Film),"[Animation, Film]",8. Library,[],[],,,,,Film released,...,,,,,,,,,,Animation

In [13]:
title_map = {
    "Even The Losers (Fka Need For Weed)": "Even the Losers",
    "Belly Of The Beast": "Belly of The Beast",
    'Brady Corbet / Mona Fastvold Project (Unt.)': "Origin of the World fka Unt. Brady Corbet & Mona Fastvold Project",

    'Silent Patient, The ': "The Silent Patient",
    '12 Minutes (Film)': "12 Minutes",
    'Bennett Miller (Unt.) ':"Unt. Bennett Miller",
    
    'Nicole Taylor Idea (Unt.)':"Evie Mcbrayne fka Unt. Nicole Taylor",
    'James Sweeney (Unt.)':"Unt. James Sweeney",
    'Into The Glory Whole':"Into the Glory whole",
    'Legend Of Georgia Mcbride, The ':"The Legend of Georgia McBride",

        'Lost Wild, The ':"The Lost Wild",


        'Beast Fiction Project (Unt.)':"Unt. Beast Fiction Project",

            'Ann Lee (Fka The Woman Clothed By The Sun) ':"The Testament of Ann Lee",



    # add more…
}

df['_id'] = df['_id'].replace(title_map)

In [14]:
df.query("_id=='The Invite'")

Empty DataFrame
Columns: [_id, ap_division_film_pt, project_stage_film_pt, ap_lead_film_pt, ap_jr_film_pt, ap_dev_film_pt, ba_status_film_pt, creative_status_film_pt, next_milestone_film_pt, option_expiration_film_pt, key_timing_film_pt, key_timing_date_film_pt, underlying_ip_film_pt, logline_film_pt, platform__distribution_film_pt, deal_type_film_pt, partners_and_vendors_film_pt, creators_film_pt, director_film_pt, writers_film_pt, producer_1_film_pt, producer_2_film_pt, cast_1_film_pt, cast_2_film_pt, cast_3_film_pt, cast_4_film_pt, ba_update_time_film_pt, creative_status_update_time_film_pt, key_timing_update_time_film_pt, slack_channel_id_film_pt, links_film_pt, division_flag_film_pt]
Index: []

[0 rows x 32 columns]

In [15]:
df.head().columns

Index(['_id', 'ap_division_film_pt', 'project_stage_film_pt',
       'ap_lead_film_pt', 'ap_jr_film_pt', 'ap_dev_film_pt',
       'ba_status_film_pt', 'creative_status_film_pt',
       'next_milestone_film_pt', 'option_expiration_film_pt',
       'key_timing_film_pt', 'key_timing_date_film_pt',
       'underlying_ip_film_pt', 'logline_film_pt',
       'platform__distribution_film_pt', 'deal_type_film_pt',
       'partners_and_vendors_film_pt', 'creators_film_pt', 'director_film_pt',
       'writers_film_pt', 'producer_1_film_pt', 'producer_2_film_pt',
       'cast_1_film_pt', 'cast_2_film_pt', 'cast_3_film_pt', 'cast_4_film_pt',
       'ba_update_time_film_pt', 'creative_status_update_time_film_pt',
       'key_timing_update_time_film_pt', 'slack_channel_id_film_pt',
       'links_film_pt', 'division_flag_film_pt'],
      dtype='object')

In [16]:
data = df.to_dict(orient='records')

In [17]:
stop

NameError: name 'stop' is not defined

In [24]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [25]:
db = client['InDevelopment']

collection = db['projects']

In [26]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

collection.delete_many({})

In [27]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 17, Inserted: 0, Modified: 1

In [28]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 12, 16, 10, 41, 17, 162791)

In [29]:
client.close()