In [1]:
### Grab Updated Sheet

In [2]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1ESVir3YAXUiX2tgxPMxfxB5MmFzp0IMWQDQvLJsbKJg/edit?resourcekey=&gid=710601441#gid=710601441"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("deal_submissions")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records()

In [3]:
### Process Data

In [4]:
import pandas as pd

df = pd.DataFrame(data)

In [5]:
df.head()

,deal_id,Timestamp,Project Title,Deal Type,Deal Description,Talent / Party,talent context,Representation,Intended Format,Email Address,Ingoing Offer,negotiating ceiling,Format/ Length/ Log-line / Based on real people/events?,BA POC,BA Updated,status,BA_deal_status,closed_date,commencement date
0,2025114_Finding Gobi_Writer_Samuel D. Hunter,11/4/2025,Finding Gobi,Writer,Guaranteed Steps: WGA Scale + 10% for a treatm...,Samuel D. Hunter,Sam is an acclaimed playwright as well as a ...,Harry Lengsfield at Untitled Email: hlengsfie...,Theatre,skyeo@annapurna.com,100000,250000,,Doug Sack,11/18/2025 0:00:00,Recieved,closed and all deals finalized.,11/17/2025 0:00:00,11/30/2025 0:00:00
1,2025116_The Silent Patient_Writer_Claire Wilson,11/6/2025,The Silent Patient,Writer,"Two guaranteed writing weeks at $25,000 each w...",Claire Wilson,Claire is a British screenwriter and TV-writ...,Sophie Dolan at LARK (same as Rita Kaljaenis r...,Film,skyeo@annapurna.com,60000,100000,,Doug Sack,11/18/2025 0:00:00,Recieved,,,
2,20251116_Voyeur_Producing_Rege-Jean Page,11/16/2025,Voyeur,Producing,Talent Deal for Rege-Jean Page to star in VOYE...,Rege-Jean Page,T/EP: Rege-Jean Page (BRIDGERTON; BLACK BAG; D...,Manager: Josh Glick @ Brillstein / j.glick@bep...,TV,dougs@annapurna.com,10000,15000,Logline: When a respected eye surgeon with a s...,Doug Sack,11/18/2025 0:00:00,Recieved,,,
3,2025111_RUSSIAN FIVE_Writer_Dave Holstein,11/1/2025,RUSSIAN FIVE,Writer,Script Deal for Dave Holstein to write a film ...,Dave Holstein,"Writer: Dave Holstein In film, Dave just wrote...",For Dave Holstein: CAA / Pete Stein / pete.ste...,Film,dougs@annapurna.com,400000,500000,The film is about the origin story of the Russ...,Doug Sack,11/18/2025 0:00:00,Recieved,,,

In [6]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['closed_date'] = pd.to_datetime(df['closed_date'])
df['commencement date'] = pd.to_datetime(df['commencement date'])
df['BA Updated'] = pd.to_datetime(df['BA Updated'])

In [7]:
df

,deal_id,Timestamp,Project Title,Deal Type,Deal Description,Talent / Party,talent context,Representation,Intended Format,Email Address,Ingoing Offer,negotiating ceiling,Format/ Length/ Log-line / Based on real people/events?,BA POC,BA Updated,status,BA_deal_status,closed_date,commencement date
0,2025114_Finding Gobi_Writer_Samuel D. Hunter,2025-11-04,Finding Gobi,Writer,Guaranteed Steps: WGA Scale + 10% for a treatm...,Samuel D. Hunter,Sam is an acclaimed playwright as well as a ...,Harry Lengsfield at Untitled Email: hlengsfie...,Theatre,skyeo@annapurna.com,100000,250000,,Doug Sack,2025-11-18,Recieved,closed and all deals finalized.,2025-11-17,2025-11-30
1,2025116_The Silent Patient_Writer_Claire Wilson,2025-11-06,The Silent Patient,Writer,"Two guaranteed writing weeks at $25,000 each w...",Claire Wilson,Claire is a British screenwriter and TV-writ...,Sophie Dolan at LARK (same as Rita Kaljaenis r...,Film,skyeo@annapurna.com,60000,100000,,Doug Sack,2025-11-18,Recieved,,NaT,NaT
2,20251116_Voyeur_Producing_Rege-Jean Page,2025-11-16,Voyeur,Producing,Talent Deal for Rege-Jean Page to star in VOYE...,Rege-Jean Page,T/EP: Rege-Jean Page (BRIDGERTON; BLACK BAG; D...,Manager: Josh Glick @ Brillstein / j.glick@bep...,TV,dougs@annapurna.com,10000,15000,Logline: When a respected eye surgeon with a s...,Doug Sack,2025-11-18,Recieved,,NaT,NaT
3,2025111_RUSSIAN FIVE_Writer_Dave Holstein,2025-11-01,RUSSIAN FIVE,Writer,Script Deal for Dave Holstein to write a film ...,Dave Holstein,"Writer: Dave Holstein In film, Dave just wrote...",For Dave Holstein: CAA / Pete Stein / pete.ste...,Film,dougs@annapurna.com,400000,500000,The film is about the origin story of the Russ...,Doug Sack,2025-11-18,Recieved,,NaT,NaT

In [8]:
from datetime import datetime

doc_list = []

for _, row in df.iterrows():

    doc = {
        '_id': row['deal_id'],
        'title': row['Project Title'],
        'division': row['Intended Format'],
        'Type': row['Deal Type'],
        'deal_description': row['Deal Description'],
        'Parties': row['Talent / Party'],
        'talent_context': row['talent context'],
        'represenation': row['Representation'],
        'requester': row['Email Address'],
        'ingoing_offer': row['Ingoing Offer'],
        'negotiating_ceiling': row['negotiating ceiling'],
        'project_details': row['Format/ Length/ Log-line / Based on real people/events?'],
        'requester': row['Email Address'],
        'requested_date': row['Timestamp'],
        'BA_POC': row['BA POC'],
        'BA_deal_status': row['BA_deal_status'],
        'status': row['status'],

#        'BA Updated': row['BA Updated'],
     #   'closed_date': row['closed_date'],
    #    'commencement_date': row['commencement date'],
        
    }

    doc_list.append(doc)

In [9]:
from datetime import datetime

doc_list_commence = []

for _, row in df.dropna(subset='commencement date').iterrows():

    doc = {
        '_id': row['deal_id'],
        'commencement_date': row['commencement date'],
        
    }

    doc_list_commence.append(doc)

In [10]:
from datetime import datetime

doc_list_closed = []

for _, row in df.dropna(subset='closed_date').iterrows():

    doc = {
        '_id': row['deal_id'],
        'closed_date': row['closed_date'],
        
    }

    doc_list_closed.append(doc)

In [11]:
from datetime import datetime

doc_list_updated = []

for _, row in df.dropna(subset='BA Updated').iterrows():

    doc = {
        '_id': row['deal_id'],
        'BA Updated': row['BA Updated'],
        
    }

    doc_list_updated.append(doc)

In [12]:
stop

NameError: name 'stop' is not defined

In [31]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [32]:
db = client['InDevelopment']

collection = db['deal_submissions']

collection.delete_many({})

In [34]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [35]:
from pymongo import UpdateOne


#####
for batch in batchify(doc_list, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 4, Modified: 0

In [36]:
from pymongo import UpdateOne


#####
for batch in batchify(doc_list_commence, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 1, Inserted: 0, Modified: 1

In [37]:
from pymongo import UpdateOne


#####
for batch in batchify(doc_list_closed, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 1, Inserted: 0, Modified: 1

In [38]:
from pymongo import UpdateOne


#####
for batch in batchify(doc_list_updated, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 4, Inserted: 0, Modified: 4

In [39]:
client.close()

In [40]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 11, 18, 8, 43, 29, 420601)