In [2]:
import pandas as pd
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [3]:

db = client['project_evaluations']

collection = db['movies']

In [12]:
from datetime import datetime

query_docs = collection.find({
    "release_date": {"$gt": "2025-09-09"},
 


})

In [14]:
df = pd.DataFrame(query_docs)

In [31]:
df.sort_values("release_date").to_clipboard()

In [ ]:
stop

In [41]:
dist_df = pd.read_clipboard()

In [43]:
dist_df

            _id            US_Dist
0    tt10374610          Lionsgate
1    tt27847051               Neon
2    tt31888477     Focus Features
3    tt32992509  Star Invest Films
4    tt33837526                NaN
..          ...                ...
639         NaN                NaN
640         NaN                NaN
641         NaN                NaN
642         NaN                NaN
643         NaN                NaN

[644 rows x 2 columns]

In [45]:
dist_df = dist_df.dropna(subset="US_Dist")

In [47]:
dist_df

            _id                              US_Dist
0    tt10374610                            Lionsgate
1    tt27847051                                 Neon
2    tt31888477                       Focus Features
3    tt32992509                    Star Invest Films
5    tt35500333            Sophie Dulac Distribution
..          ...                                  ...
485  tt32328541                         Warner Bros.
486  tt21361444  Walt Disney Studios Motion Pictures
487  tt33088418  Walt Disney Studios Motion Pictures
489   tt3095356                 20th Century Studios
490   tt5637536                 20th Century Studios

[185 rows x 2 columns]

In [49]:
final_export = dist_df.to_dict(orient='records')

In [51]:
final_export

[{'_id': 'tt10374610', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt27847051', 'US_Dist': 'Neon'},
 {'_id': 'tt31888477', 'US_Dist': 'Focus Features'},
 {'_id': 'tt32992509', 'US_Dist': 'Star Invest Films'},
 {'_id': 'tt35500333', 'US_Dist': 'Sophie Dulac Distribution'},
 {'_id': 'tt23157384', 'US_Dist': 'UTA Independent Film Group'},
 {'_id': 'tt33039440', 'US_Dist': 'Netflix'},
 {'_id': 'tt35652650', 'US_Dist': 'Netflix'},
 {'_id': 'tt15799524', 'US_Dist': 'MUBI'},
 {'_id': 'tt1934397', 'US_Dist': 'Level 33 Entertainment'},
 {'_id': 'tt20222166', 'US_Dist': 'Bleecker Street Media'},
 {'_id': 'tt26394837', 'US_Dist': 'Aura Entertainment'},
 {'_id': 'tt29567402', 'US_Dist': 'Magnolia Pictures'},
 {'_id': 'tt31101921', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt31883677', 'US_Dist': 'Verve Pictures'},
 {'_id': 'tt36607192', 'US_Dist': 'Toei Company'},
 {'_id': 'tt29644189', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt13650700', 'US_Dist': 'Columbia Pictures'},
 {'_id': 'tt27722618', 'US_Dist': 'Netflix'},
 {'_id': 'tt36667493', 'US_Dist': 'Kino Lorber'},
 {'_id': 'tt15431864', 'US_Dist': 'Angel'},
 {'_id': 'tt20990442', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt21110654', 'US_Dist': 'HBO Max'},
 {'_id': 'tt31495504', 'US_Dist': 'Amazon MGM Studios'},
 {'_id': 'tt33028976', 'US_Dist': 'Well Go USA Entertainment'},
 {'_id': 'tt21103218', 'US_Dist': 'Apple TV+'},
 {'_id': 'tt27550504', 'US_Dist': 'Magnolia Pictures'},
 {'_id': 'tt27629220', 'US_Dist': 'Blue Fox Entertainment'},
 {'_id': 'tt30472557', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt32985279', 'US_Dist': 'Netflix'},
 {'_id': 'tt33057137', 'US_Dist': 'Well Go USA Entertainment'},
 {'_id': 'tt32214143', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt1527793', 'US_Dist': 'Neon'},
 {'_id': 'tt30144839', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt28671344', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt29213475', 'US_Dist': 'Neon'},
 {'_id': 'tt30268321', 'US_Dist': 'Sony Pictures Classics'},
 {'_id': 'tt32306048', 'US_Dist': 'Netflix'},
 {'_id': 'tt7574556', 'US_Dist': 'Vertical Entertainment'},
 {'_id': 'tt18392014', 'US_Dist': 'Amazon Prime Video'},
 {'_id': 'tt32886599', 'US_Dist': 'MUBI'},
 {'_id': 'tt36491653', 'US_Dist': 'Neon'},
 {'_id': 'tt11214558', 'US_Dist': 'A24'},
 {'_id': 'tt14999684', 'US_Dist': 'Neon'},
 {'_id': 'tt32129665', 'US_Dist': 'Netflix'},
 {'_id': 'tt32376165', 'US_Dist': 'Netflix'},
 {'_id': 'tt33549447', 'US_Dist': 'Focus Features'},
 {'_id': 'tt4627382', 'US_Dist': 'Paramount Pictures'},
 {'_id': 'tt9362736', 'US_Dist': 'MUBI'},
 {'_id': 'tt31688586', 'US_Dist': 'Netflix'},
 {'_id': 'tt6604188', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt29468874', 'US_Dist': 'Well Go USA Entertainment'},
 {'_id': 'tt7130300', 'US_Dist': 'Netflix'},
 {'_id': 'tt18382850', 'US_Dist': 'A24'},
 {'_id': 'tt30400277', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt31511689', 'US_Dist': 'Paramount Pictures'},
 {'_id': 'tt32159989', 'US_Dist': 'Amazon MGM Studios'},
 {'_id': 'tt34962891', 'US_Dist': 'Netflix'},
 {'_id': 'tt29002950', 'US_Dist': 'Janus Films'},
 {'_id': 'tt29003152', 'US_Dist': 'Janus Films'},
 {'_id': 'tt32063098', 'US_Dist': 'Netflix'},
 {'_id': 'tt33255286', 'US_Dist': 'StudioCanal'},
 {'_id': 'tt26720001', 'US_Dist': 'Briarcliff Entertainment'},
 {'_id': 'tt27543578', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt33455099', 'US_Dist': 'MUBI'},
 {'_id': 'tt1312221', 'US_Dist': 'Netflix'},
 {'_id': 'tt27773954', 'US_Dist': 'Briarcliff Entertainment'},
 {'_id': 'tt32536315', 'US_Dist': 'Sony Pictures Classics'},
 {'_id': 'tt33502160', 'US_Dist': 'Hulu'},
 {'_id': 'tt31844586', 'US_Dist': 'Screen Gems'},
 {'_id': 'tt31923069', 'US_Dist': '20th Century Studios'},
 {'_id': 'tt33088452', 'US_Dist': 'Paramount Pictures'},
 {'_id': 'tt12300742', 'US_Dist': 'Focus Features'},
 {'_id': 'tt12583926', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt32304349', 'US_Dist': 'Magnolia Pictures'},
 {'_id': 'tt14107334', 'US_Dist': 'Paramount Pictures'},
 {'_id': 'tt31227572', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt29768334', 'US_Dist': 'Netflix'},
 {'_id': 'tt22525442', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt27604215', 'US_Dist': 'Netflix'},
 {'_id': 'tt29567915', 'US_Dist': 'Sony Pictures Classics'},
 {'_id': 'tt31727267', 'US_Dist': 'Metro-Goldwyn-Mayer (MGM)'},
 {'_id': 'tt31851518', 'US_Dist': 'Sony Pictures Classics'},
 {'_id': 'tt32323252', 'US_Dist': 'Black Bear'},
 {'_id': 'tt4712810', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt32332404', 'US_Dist': 'Neon'},
 {'_id': 'tt30446847', 'US_Dist': 'Netflix'},
 {'_id': 'tt19847976', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt33053440', 'US_Dist': 'Netflix'},
 {'_id': 'tt35363310', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt14142060', 'US_Dist': 'Searchlight Pictures'},
 {'_id': 'tt35114460', 'US_Dist': 'Sony Pictures Classics'},
 {'_id': 'tt14364480', 'US_Dist': 'Netflix'},
 {'_id': 'tt24950660', 'US_Dist': 'A24'},
 {'_id': 'tt26443597', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt33852162', 'US_Dist': 'Sony Pictures Classics'},
 {'_id': 'tt14905854', 'US_Dist': 'Focus Features'},
 {'_id': 'tt32321317', 'US_Dist': 'A24'},
 {'_id': 'tt29232158', 'US_Dist': 'Netflix'},
 {'_id': 'tt30274401', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt33350512', 'US_Dist': 'IFC Films'},
 {'_id': 'tt30096221', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt23172090', 'US_Dist': 'Roadside Attractions'},
 {'_id': 'tt1757678', 'US_Dist': '20th Century Studios'},
 {'_id': 'tt23572848', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt27543632', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt34491649', 'US_Dist': 'Angel'},
 {'_id': 'tt30343021', 'US_Dist': 'Focus Features'},
 {'_id': 'tt32916440', 'US_Dist': 'A24'},
 {'_id': 'tt21272942', 'US_Dist': 'Angel'},
 {'_id': 'tt32655030', 'US_Dist': 'Universal Pictures International (UPI)'},
 {'_id': 'tt14850054', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt32141377', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt31050594', 'US_Dist': 'Amazon MGM Studios'},
 {'_id': 'tt32338669', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt8036976', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt27613895', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt32897959', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt34888646', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt27047903', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt26443616', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt30851137', 'US_Dist': 'IMAX'},
 {'_id': 'tt12042730', 'US_Dist': 'Amazon MGM Studios'},
 {'_id': 'tt17042980', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt21285562', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt28650488', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt33978029', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt11378946', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt33612209', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt16911616', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt36586020', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt17490712', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt30825738', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt0427340', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt32093575', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt15047880', 'US_Dist': 'Universal Pictures International (UPI)'},
 {'_id': 'tt29355505', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt8814476', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt32890033', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt27419466', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt33764258', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt22084616', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt29356163', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt27165187', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt32393988', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt1756855', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt34890576', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt32588798', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt31450459', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt32261958', 'US_Dist': 'Amazon MGM Studios'},
 {'_id': 'tt18259538', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt35621542', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt2321555', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt32565993', 'US_Dist': 'Amazon MGM Studios'},
 {'_id': 'tt32558705', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt34966140', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt32432428', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt26735127', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt21357150', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt31378509', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt35514120', 'US_Dist': 'Focus Features'},
 {'_id': 'tt6779038', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt32557122', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt34512981', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt4540534', 'US_Dist': 'TriStar Pictures'},
 {'_id': 'tt16744566', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt5795232', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt29873948', 'US_Dist': 'Sony Pictures Releasing'},
 {'_id': 'tt32021219', 'US_Dist': 'Lionsgate'},
 {'_id': 'tt28069611', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt36416299', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt26443610', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt16360004', 'US_Dist': 'Columbia Pictures'},
 {'_id': 'tt6113186', 'US_Dist': 'Universal Pictures'},
 {'_id': 'tt37833661', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt36495786', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt31512072', 'US_Dist': 'Paramount Pictures International'},
 {'_id': 'tt19850008', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt7008874', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt26680923', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt32328541', 'US_Dist': 'Warner Bros.'},
 {'_id': 'tt21361444', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt33088418', 'US_Dist': 'Walt Disney Studios Motion Pictures'},
 {'_id': 'tt3095356', 'US_Dist': '20th Century Studios'},
 {'_id': 'tt5637536', 'US_Dist': '20th Century Studios'}]

In [53]:
from pymongo import UpdateOne

operations = [
    UpdateOne(
        {"_id": doc["_id"]},
        {"$set": doc},
        upsert=True
    ) for doc in final_export
]

result = collection.bulk_write(operations)
print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 185, Inserted: 0, Modified: 185